# Generated by Django 5.2.8 on 2025-11-21 17:40

import axis_backend.utils.generators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Document title", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Document description and purpose",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("contract", "Contract"),
                            ("certification", "Certification"),
                            ("kpi_report", "KPI Report"),
                            ("feedback_summary", "Feedback Summary"),
                            ("billing_report", "Billing Report"),
                            ("utilization_report", "Utilization Report"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Document classification",
                        max_length=30,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Document file location (cloud storage URL)",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        help_text="MIME type (e.g., 'application/pdf')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="Document version number",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this is the current version",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Published", "Published"),
                            ("Archived", "Archived"),
                            ("Expired", "Expired"),
                        ],
                        db_index=True,
                        default="Draft",
                        help_text="Document publication status",
                        max_length=20,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Document expiration date",
                        null=True,
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Restricted access document",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Document tags for categorization",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Document-specific attributes",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated client",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated contract",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="contracts.contract",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to previous version",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="documents.document",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who uploaded document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="documents_title_3f6c9c_idx"),
                    models.Index(fields=["type"], name="documents_type_e7d6d1_idx"),
                    models.Index(fields=["status"], name="documents_status_f31a08_idx"),
                    models.Index(
                        fields=["client"], name="documents_client__4ad244_idx"
                    ),
                    models.Index(
                        fields=["contract"], name="documents_contrac_046399_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="documents_uploade_aad805_idx"
                    ),
                    models.Index(
                        fields=["is_confidential"], name="documents_is_conf_4ece8e_idx"
                    ),
                    models.Index(
                        fields=["is_latest"], name="documents_is_late_ccb748_idx"
                    ),
                    models.Index(
                        fields=["expiry_date"], name="documents_expiry__8f271f_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="documents_deleted_5f96ec_idx"
                    ),
                ],
            },
        ),
    ]
