# Generated by Django 5.2.8 on 2025-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded document file (alternative to URL)",
                max_length=500,
                null=True,
                upload_to="documents/%Y/%m/%d/",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Document file location (cloud storage URL, alternative to file upload)",
                max_length=500,
                null=True,
            ),
        ),
    ]
