# Generated by Django 5.2.8 on 2025-11-21 17:40

import axis_backend.utils.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("Delete", "Delete"),
                            ("Login", "Login"),
                            ("Logout", "Logout"),
                            ("Approve", "Approve"),
                            ("Reject", "Reject"),
                            ("List", "List"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Action performed",
                        max_length=20,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of entity affected (e.g., 'Client', 'Contract')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID of affected entity",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional action context and data",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Client user agent string", null=True
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When action occurred",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EntityChange",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Entity model name (e.g., 'Client', 'Contract')",
                        max_length=100,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        db_index=True,
                        help_text="Entity unique identifier",
                        max_length=25,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("Delete", "Delete"),
                            ("Restore", "Restore"),
                            ("Archive", "Archive"),
                            ("Unarchive", "Unarchive"),
                            ("Deactivate", "Deactivate"),
                            ("Activate", "Activate"),
                        ],
                        db_index=True,
                        help_text="Type of change operation",
                        max_length=20,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When change occurred",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="User ID who made change",
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, help_text="Explanation for change", null=True
                    ),
                ),
                (
                    "old_data",
                    models.JSONField(
                        blank=True, help_text="Entity state before change", null=True
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True, help_text="Entity state after change", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional change context",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether change record is active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entity Change",
                "verbose_name_plural": "Entity Changes",
                "db_table": "entity_changes",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="FieldChange",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_index=True, help_text="Name of changed field", max_length=100
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Previous field value", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="New field value", null=True
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("Create", "Create"),
                            ("Update", "Update"),
                            ("Delete", "Delete"),
                            ("Restore", "Restore"),
                            ("Archive", "Archive"),
                            ("Unarchive", "Unarchive"),
                            ("Deactivate", "Deactivate"),
                            ("Activate", "Activate"),
                        ],
                        db_index=True,
                        help_text="Type of field change",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Change",
                "verbose_name_plural": "Field Changes",
                "db_table": "field_changes",
                "ordering": ["entity_change", "field_name"],
            },
        ),
    ]
