# Generated by Django 5.2.8 on 2025-11-21 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who performed action",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["entity_type"], name="entity_chan_entity__bf9d0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["entity_id"], name="entity_chan_entity__0fedb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["entity_type", "entity_id", "changed_at"],
                name="entity_chan_entity__2e104f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["changed_at"], name="entity_chan_changed_c07c8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["changed_by"], name="entity_chan_changed_514734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["change_type"], name="entity_chan_change__3cbb7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["is_active"], name="entity_chan_is_acti_e36688_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entitychange",
            index=models.Index(
                fields=["deleted_at"], name="entity_chan_deleted_0902c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitychange",
            constraint=models.UniqueConstraint(
                fields=("entity_type", "entity_id", "changed_at"),
                name="unique_entity_change",
            ),
        ),
        migrations.AddField(
            model_name="fieldchange",
            name="entity_change",
            field=models.ForeignKey(
                help_text="Parent entity change record",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_changes",
                to="audit.entitychange",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["timestamp"], name="audit_logs_timesta_423be6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["entity_type", "entity_id"],
                name="audit_logs_entity__d4c2e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user"], name="audit_logs_user_id_73c422_idx"),
        ),
        migrations.AddIndex(
            model_name="fieldchange",
            index=models.Index(
                fields=["entity_change"], name="field_chang_entity__213eb3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldchange",
            index=models.Index(
                fields=["field_name"], name="field_chang_field_n_d49771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldchange",
            index=models.Index(
                fields=["change_type"], name="field_chang_change__a525a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fieldchange",
            index=models.Index(
                fields=["deleted_at"], name="field_chang_deleted_e4c732_idx"
            ),
        ),
    ]
