# Generated by Django 5.2.8 on 2025-11-21 17:15

import axis_backend.utils.generators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Optional username for display",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary email address for authentication",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Hashed password (null for OAuth-only accounts)",
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "email_verified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when email was verified",
                        null=True,
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Most recent successful login",
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("English", "English"),
                            ("Spanish", "Spanish"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Other", "Other"),
                        ],
                        help_text="Interface language preference",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="IANA timezone for localization",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_two_factor_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Two-factor authentication enabled",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("Banned", "Banned"),
                            ("Pending Verification", "Pending Verification"),
                            ("Inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="Pending Verification",
                        help_text="Account lifecycle state",
                        max_length=30,
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp of last status change",
                        null=True,
                    ),
                ),
                (
                    "inactive_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation if status is INACTIVE",
                        null=True,
                    ),
                ),
                (
                    "suspension_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation if status is SUSPENDED",
                        null=True,
                    ),
                ),
                (
                    "ban_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation if status is BANNED",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for custom user attributes",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Soft deletion timestamp",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="Account type (e.g., 'oauth', 'oidc')", max_length=50
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Identity provider name (e.g., 'microsoft', 'google')",
                        max_length=50,
                    ),
                ),
                (
                    "provider_account_id",
                    models.CharField(
                        db_index=True,
                        help_text="User's unique identifier from provider",
                        max_length=255,
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Token for obtaining new access tokens",
                        null=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True,
                        help_text="Current access token for API calls",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.IntegerField(
                        blank=True,
                        help_text="Unix timestamp when access token expires",
                        null=True,
                    ),
                ),
                (
                    "token_type",
                    models.CharField(
                        blank=True,
                        help_text="Token type (e.g., 'Bearer')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "scope",
                    models.TextField(
                        blank=True, help_text="Granted OAuth scopes", null=True
                    ),
                ),
                (
                    "id_token",
                    models.TextField(
                        blank=True, help_text="OpenID Connect ID token", null=True
                    ),
                ),
                (
                    "session_state",
                    models.CharField(
                        blank=True,
                        help_text="Provider session state identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Last successful authentication via this provider",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this provider account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "accounts",
                "ordering": ["-last_login_at"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Permission identifier (e.g., 'view_clients', 'edit_contracts')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Permission scope and purpose", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="permissions_name_6a4248_idx"),
                    models.Index(
                        fields=["deleted_at"], name="permissions_deleted_2f9bef_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "full_name",
                    models.CharField(help_text="Complete legal name", max_length=255),
                ),
                (
                    "preferred_name",
                    models.CharField(
                        blank=True,
                        help_text="Preferred name or nickname for informal use",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dob",
                    models.DateField(blank=True, help_text="Date of birth", null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        help_text="Gender identification",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary phone number",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Residential or mailing address",
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact person full name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Emergency contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("English", "English"),
                            ("Spanish", "Spanish"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Preferred communication language",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Preferred contact channel",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True,
                        help_text="Profile photo URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional profile attributes",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated user account (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Role name (e.g., 'Admin', 'Manager', 'Staff')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Role purpose and responsibilities",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="roles_name_a96913_idx"),
                    models.Index(
                        fields=["deleted_at"], name="roles_deleted_772cbe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        help_text="Permission being granted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="authentication.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role receiving permission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="authentication.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "db_table": "role_permissions",
                "ordering": ["role", "permission"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        db_index=True,
                        help_text="Unique session identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "expires",
                    models.DateTimeField(
                        db_index=True, help_text="Session expiration timestamp"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP address when session created",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Client user agent string", null=True
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Session validity flag (for manual invalidation)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "db_table": "sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "role",
                    models.ForeignKey(
                        help_text="Role being assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="authentication.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["user", "role"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="users_status_9ca66f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login_at"], name="users_last_lo_6ea639_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_two_factor_enabled"], name="users_is_two__4de082_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["status_changed_at"], name="users_status__c5ee4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["deleted_at"], name="users_deleted_e48316_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["user"], name="accounts_user_id_6786b5_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["provider"], name="accounts_provide_16df8c_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["provider_account_id"], name="accounts_provide_6ee13c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["last_login_at"], name="accounts_last_lo_6d7636_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["deleted_at"], name="accounts_deleted_ab12c0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_account_id"),
                name="unique_provider_account",
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["full_name"], name="profiles_full_na_caac6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["preferred_language"], name="profiles_preferr_d59f23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["preferred_contact_method"], name="profiles_preferr_fbb789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["deleted_at"], name="profiles_deleted_9c701c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["role"], name="role_permis_role_id_0ea48f_idx"),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(
                fields=["permission"], name="role_permis_permiss_96a6c9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_role_permission"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["session_token"], name="sessions_session_7633cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["user"], name="sessions_user_id_7acd24_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["expires"], name="sessions_expires_f3213c_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(fields=["is_valid"], name="sessions_is_vali_6729de_idx"),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["created_at"], name="sessions_created_0a2de2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["user"], name="user_roles_user_id_05df60_idx"),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="user_roles_role_id_0b583b_idx"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="unique_user_role"
            ),
        ),
    ]
