# Generated by Django 5.2.8 on 2025-11-23 15:02

import axis_backend.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserClient",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "granted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When authorization was granted"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Reason or notes for this authorization",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client being authorized for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_authorizations",
                        to="clients.client",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who granted this authorization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_authorizations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User being authorized",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Client Authorization",
                "verbose_name_plural": "User Client Authorizations",
                "db_table": "user_clients",
                "ordering": ["user", "client"],
                "indexes": [
                    models.Index(
                        fields=["user", "client"], name="user_client_user_id_8627f2_idx"
                    ),
                    models.Index(
                        fields=["user"], name="user_client_user_id_b5c33e_idx"
                    ),
                    models.Index(
                        fields=["client"], name="user_client_client__fda23e_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="user_client_deleted_cffa4e_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("user", "client"),
                        name="unique_user_client_active",
                    )
                ],
            },
        ),
    ]
