# Generated by Django 5.2.8 on 2025-11-21 17:15

import axis_backend.utils.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True, help_text="Contract effective start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True, help_text="Contract expiration date"
                    ),
                ),
                (
                    "renewal_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when contract is eligible for renewal",
                        null=True,
                    ),
                ),
                (
                    "billing_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Contract value or billing rate",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UGX",
                        help_text="ISO 4217 currency code (e.g., 'UGX', 'USD')",
                        max_length=3,
                    ),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        blank=True,
                        help_text="Billing cycle (e.g., 'Monthly', 'Quarterly')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        help_text="Payment conditions and due date terms",
                        null=True,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("Overdue", "Overdue"),
                            ("Cancelled", "Cancelled"),
                            ("Refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="Pending",
                        help_text="Current payment state",
                        max_length=20,
                    ),
                ),
                (
                    "last_billing_date",
                    models.DateField(
                        blank=True, help_text="Most recent billing date", null=True
                    ),
                ),
                (
                    "next_billing_date",
                    models.DateField(
                        blank=True, help_text="Upcoming billing date", null=True
                    ),
                ),
                (
                    "is_renewable",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Contract eligible for renewal",
                    ),
                ),
                (
                    "is_auto_renew",
                    models.BooleanField(
                        default=False, help_text="Automatic renewal enabled"
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        help_text="Signed contract document location",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        blank=True,
                        help_text="Authorized signatory name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, help_text="Contract execution timestamp", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Terminated", "Terminated"),
                            ("Renewed", "Renewed"),
                            ("Pending", "Pending"),
                            ("Draft", "Draft"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Current contract lifecycle state",
                        max_length=20,
                    ),
                ),
                (
                    "termination_reason",
                    models.TextField(
                        blank=True,
                        help_text="Explanation if contract terminated early",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal contract notes and observations",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client organization under contract",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "contracts",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["client"], name="contracts_client__733d5c_idx"
                    ),
                    models.Index(fields=["status"], name="contracts_status_093df1_idx"),
                    models.Index(
                        fields=["start_date"], name="contracts_start_d_b96943_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="contracts_end_dat_9bf3b4_idx"
                    ),
                    models.Index(
                        fields=["payment_status"], name="contracts_payment_f617ae_idx"
                    ),
                    models.Index(
                        fields=["is_renewable"], name="contracts_is_rene_e95ed2_idx"
                    ),
                    models.Index(
                        fields=["next_billing_date"],
                        name="contracts_next_bi_7728ce_idx",
                    ),
                    models.Index(
                        fields=["deleted_at"], name="contracts_deleted_dd0de1_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="end_date_after_start_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("billing_rate__gte", 0)),
                        name="billing_rate_non_negative",
                    ),
                ],
            },
        ),
    ]
