# Generated by Django 5.2.8 on 2025-11-21 17:40

import axis_backend.utils.generators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Industry name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Standard classification code (NAICS, ISIC, etc.)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Industry description and scope",
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Reference ID from external classification system",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional attributes (e.g., tags, categories)",
                        null=True,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent industry in hierarchy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="clients.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "db_table": "industries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Legal or operating name of organization",
                        max_length=255,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        help_text="Primary organizational email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Public website URL",
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Physical office address", null=True
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(
                        blank=True,
                        help_text="Invoicing address if different from physical",
                        null=True,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        blank=True,
                        help_text="IANA timezone identifier (e.g., 'Africa/Kampala')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="Tax identification or registration number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        help_text="Full name of primary contact",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of primary contact person",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone of primary contact person",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Pending", "Pending"),
                            ("Archived", "Archived"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Current operational status",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Preferred communication channel",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Organization verification status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal observations and important details",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for custom attributes",
                        null=True,
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Business sector classification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="clients.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(fields=["name"], name="industries_name_285c10_idx"),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(fields=["code"], name="industries_code_6a00b7_idx"),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(fields=["parent"], name="industries_parent__a46b06_idx"),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(
                fields=["external_id"], name="industries_externa_aa388a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="industry",
            index=models.Index(
                fields=["deleted_at"], name="industries_deleted_8073f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="clients_name_0bc5f0_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="clients_email_4c8bec_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["status"], name="clients_status_98ee60_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["industry"], name="clients_industr_e0c9f7_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["is_verified"], name="clients_is_veri_99fdf2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["preferred_contact_method"], name="clients_preferr_6fc14a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["deleted_at"], name="clients_deleted_c20e8e_idx"
            ),
        ),
    ]
