# Generated by Django 5.2.8 on 2025-11-25 13:59

import axis_backend.utils.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="last_contact_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Most recent interaction or communication date",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="parent_client",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent organization for client hierarchy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsidiaries",
                to="clients.client",
            ),
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Contact person's first name", max_length=100
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Contact person's last name", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Mobile phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary Contact"),
                            ("Billing", "Billing Contact"),
                            ("Technical", "Technical Contact"),
                            ("Executive", "Executive"),
                            ("Legal", "Legal Contact"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        default="Other",
                        help_text="Contact's role within organization",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Job title (e.g., 'CEO', 'CFO', 'Project Manager')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="Department or division",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Designate as primary contact for client",
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("Email", "Email"),
                            ("Phone", "Phone"),
                            ("SMS", "SMS"),
                            ("WhatsApp", "WhatsApp"),
                            ("Other", "Other"),
                        ],
                        default="Email",
                        help_text="Preferred communication channel",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Contact is currently reachable",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about this contact",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible storage for custom attributes",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Parent client organization",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Contact",
                "verbose_name_plural": "Client Contacts",
                "db_table": "client_contacts",
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="ClientActivity",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("Note", "Note"),
                            ("Call", "Phone Call"),
                            ("Email", "Email"),
                            ("Meeting", "Meeting"),
                            ("StatusChange", "Status Change"),
                            ("ContractSigned", "Contract Signed"),
                            ("PaymentReceived", "Payment Received"),
                            ("DocumentUploaded", "Document Uploaded"),
                            ("Verification", "Verification Event"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of activity or interaction",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief activity title or summary", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed activity description or notes",
                        null=True,
                    ),
                ),
                (
                    "activity_date",
                    models.DateTimeField(
                        db_index=True, help_text="When this activity occurred"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Type-specific data (call duration, email subject, etc.)",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client this activity relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="clients.client",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific client contact involved (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="clients.clientcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Activity",
                "verbose_name_plural": "Client Activities",
                "db_table": "client_activities",
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientTag",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Tag label (e.g., 'VIP', 'Enterprise')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of name", unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Hex color code for visual identification (e.g., '#10B981')",
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Purpose and usage guidance for this tag",
                        null=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="System-managed tag that cannot be deleted by users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Tag",
                "verbose_name_plural": "Client Tags",
                "db_table": "client_tags",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="client_tags_name_d5e350_idx"),
                    models.Index(fields=["slug"], name="client_tags_slug_7eb75e_idx"),
                    models.Index(
                        fields=["is_system"], name="client_tags_is_syst_5bad4f_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="client",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Flexible categorization tags (VIP, Enterprise, etc.)",
                related_name="clients",
                to="clients.clienttag",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["parent_client"], name="clients_parent__de4f1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["last_contact_date"], name="clients_last_co_103e02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(
                fields=["client", "is_primary"], name="client_cont_client__6d1ddb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(
                fields=["client", "role"], name="client_cont_client__a572f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(fields=["email"], name="client_cont_email_c09782_idx"),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(
                fields=["is_active"], name="client_cont_is_acti_047bde_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.UniqueConstraint(
                fields=("client", "email"), name="unique_contact_email_per_client"
            ),
        ),
        migrations.AddIndex(
            model_name="clientactivity",
            index=models.Index(
                fields=["client", "-activity_date"],
                name="client_acti_client__798f1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientactivity",
            index=models.Index(
                fields=["client", "activity_type"],
                name="client_acti_client__37bb3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clientactivity",
            index=models.Index(
                fields=["activity_type", "-activity_date"],
                name="client_acti_activit_21185e_idx",
            ),
        ),
    ]
