# Generated by Django 5.2.8 on 2025-11-21 17:40

import axis_backend.utils.generators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
        ("persons", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Category name (e.g., 'Counseling', 'Legal Assistance')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Category purpose and scope", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional category attributes",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "db_table": "service_categories",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="service_cat_name_263675_idx"),
                    models.Index(
                        fields=["deleted_at"], name="service_cat_deleted_744a9d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Provider name or organization",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Counselor", "Counselor"),
                            ("Clinic", "Clinic"),
                            ("Hotline", "Hotline"),
                            ("Coach", "Coach"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Provider type classification",
                        max_length=20,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        help_text="Physical location or service area",
                        null=True,
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Certifications and credentials",
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True, default=list, help_text="Areas of expertise"
                    ),
                ),
                (
                    "availability",
                    models.JSONField(
                        blank=True, help_text="Available hours and capacity", null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        help_text="Average rating (0-5 scale)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Provider verification status",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                            ("Suspended", "Suspended"),
                            ("Resigned", "Resigned"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Provider availability status",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional provider information",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Provider",
                "verbose_name_plural": "Service Providers",
                "db_table": "service_providers",
                "ordering": ["-rating", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="service_pro_name_2520af_idx"),
                    models.Index(fields=["type"], name="service_pro_type_8d50e7_idx"),
                    models.Index(
                        fields=["status"], name="service_pro_status_a75042_idx"
                    ),
                    models.Index(
                        fields=["is_verified"], name="service_pro_is_veri_42612d_idx"
                    ),
                    models.Index(
                        fields=["rating"], name="service_pro_rating_c6e63c_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="service_pro_deleted_c57103_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Service name (e.g., 'Individual Counseling', 'Legal Consultation')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed service description and scope",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Pending", "Pending"),
                            ("Archived", "Archived"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Service availability status",
                        max_length=20,
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Typical session duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum participants (for group sessions)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(
                        blank=True,
                        help_text="Requirements or conditions for service access",
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Visible in public service catalog",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Service cost (if applicable)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Service-specific attributes and configuration",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Service category classification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="services_app.servicecategory",
                    ),
                ),
                (
                    "service_provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default provider for this service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="services_app.serviceprovider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceSession",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        db_index=True, help_text="Scheduled session date and time"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Actual completion timestamp", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Rescheduled", "Rescheduled"),
                            ("Completed", "Completed"),
                            ("Canceled", "Canceled"),
                            ("No Show", "No Show"),
                            ("Postponed", "Postponed"),
                        ],
                        db_index=True,
                        default="Scheduled",
                        help_text="Session status",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Session notes (confidential)", null=True
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True, help_text="Post-session feedback", null=True
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        blank=True,
                        help_text="Actual session duration in minutes",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Session location or platform",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True, help_text="Reason if canceled", null=True
                    ),
                ),
                (
                    "reschedule_count",
                    models.IntegerField(
                        default=0, help_text="Number of times rescheduled"
                    ),
                ),
                (
                    "is_group_session",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is a group session",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Session-specific data",
                        null=True,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        help_text="Person (employee or dependent) receiving service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_sessions",
                        to="persons.person",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        help_text="Provider delivering service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="services_app.serviceprovider",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service being provided",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="services_app.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Session",
                "verbose_name_plural": "Service Sessions",
                "db_table": "service_sessions",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionFeedback",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Session rating (1-5 scale)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Written feedback", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional feedback data",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        help_text="Session being rated",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_entries",
                        to="services_app.servicesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Feedback",
                "verbose_name_plural": "Session Feedback",
                "db_table": "session_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceAssignment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        help_text="Assignment status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True, help_text="Service availability start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Service availability end date", null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Once", "Once"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        help_text="Expected service frequency",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Assignment-specific configuration",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client receiving service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_assignments",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract under which service is provided",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_assignments",
                        to="contracts.contract",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Assigned service",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="services_app.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Assignment",
                "verbose_name_plural": "Service Assignments",
                "db_table": "service_assignments",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["service"], name="service_ass_service_bd83d2_idx"
                    ),
                    models.Index(
                        fields=["contract"], name="service_ass_contrac_379f52_idx"
                    ),
                    models.Index(
                        fields=["client"], name="service_ass_client__c0863c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="service_ass_status_87ab47_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="service_ass_start_d_e7b9bd_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="service_ass_deleted_b6e550_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["name"], name="services_name_a79f61_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["category"], name="services_categor_a61a21_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["status"], name="services_status_6676e7_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_public"], name="services_is_publ_0f7c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_provider"], name="services_service_4be63d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["deleted_at"], name="services_deleted_8e32dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["service"], name="service_ses_service_75a179_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["provider"], name="service_ses_provide_8e0e33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["person"], name="service_ses_person__987ca8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(fields=["status"], name="service_ses_status_b40de8_idx"),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["scheduled_at"], name="service_ses_schedul_92e538_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["is_group_session"], name="service_ses_is_grou_0664c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicesession",
            index=models.Index(
                fields=["deleted_at"], name="service_ses_deleted_9afc51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionfeedback",
            index=models.Index(
                fields=["session"], name="session_fee_session_93e43a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionfeedback",
            index=models.Index(fields=["rating"], name="session_fee_rating_b0e8ba_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionfeedback",
            index=models.Index(
                fields=["deleted_at"], name="session_fee_deleted_25b4d0_idx"
            ),
        ),
    ]
