# Generated by Django 5.2.8 on 2025-11-21 17:15

import axis_backend.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Admin", "Admin"),
                            ("Manager", "Manager"),
                            ("Staff", "Staff"),
                            ("Volunteer", "Volunteer"),
                        ],
                        db_index=True,
                        help_text="Role within employer organization (for service allocation)",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        help_text="Employment start date with client organization",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Employment end date (when no longer eligible for EAP)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                            ("Suspended", "Suspended"),
                            ("Resigned", "Resigned"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Employment status (determines EAP eligibility)",
                        max_length=20,
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Employee role qualifications (context for counseling)",
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Work areas or departments (for targeted EAP programs)",
                    ),
                ),
                (
                    "preferred_working_hours",
                    models.JSONField(
                        blank=True,
                        help_text="Work schedule for session scheduling (e.g., {'monday': '9-17'})",
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact person name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Emergency contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional employee context (department, manager, etc.)",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Employer organization providing EAP benefits",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff",
                        to="clients.client",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="Personal demographic information",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff",
                        to="authentication.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User account for EAP portal access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Member",
                "verbose_name_plural": "Staff Members",
                "db_table": "staff",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["user"], name="staff_user_id_419644_idx"),
                    models.Index(fields=["client"], name="staff_client__a26024_idx"),
                    models.Index(fields=["profile"], name="staff_profile_80b567_idx"),
                    models.Index(fields=["role"], name="staff_role_a521aa_idx"),
                    models.Index(fields=["status"], name="staff_status_c91b08_idx"),
                    models.Index(
                        fields=["start_date"], name="staff_start_d_ad5674_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="staff_deleted_618343_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="staff_end_date_after_start_date",
                    )
                ],
            },
        ),
    ]
