# Generated by Django 5.2.8 on 2025-11-21 17:15

import axis_backend.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("staff", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("Child", "Child"),
                            ("Spouse", "Spouse"),
                            ("Parent", "Parent"),
                            ("Sibling", "Sibling"),
                            ("Grandparent", "Grandparent"),
                            ("Guardian", "Guardian"),
                            ("Friend", "Friend"),
                            ("Neighbor", "Neighbor"),
                            ("Cousin", "Cousin"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Relationship to staff member (spouse, child, parent, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_staff_link",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a direct staff-to-staff link (e.g., spouse also employed)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Pending", "Pending"),
                            ("Archived", "Archived"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Beneficiary status (determines service eligibility)",
                        max_length=20,
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Most recent service session date",
                        null=True,
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("English", "English"),
                            ("Spanish", "Spanish"),
                            ("French", "French"),
                            ("German", "German"),
                            ("Other", "Other"),
                        ],
                        help_text="Preferred language for services",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about beneficiary (allergies, special needs, etc.)",
                        null=True,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Guardian user for minors (parent/guardian portal access)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardianships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="Personal demographic information",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiary",
                        to="authentication.profile",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        help_text="Staff member (employee) to whom this beneficiary is related",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaries",
                        to="staff.staff",
                    ),
                ),
                (
                    "user_link",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account for adult beneficiaries with direct portal access",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="beneficiary_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiary",
                "verbose_name_plural": "Beneficiaries",
                "db_table": "beneficiaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["staff"], name="beneficiari_staff_i_b4fc23_idx"
                    ),
                    models.Index(
                        fields=["profile"], name="beneficiari_profile_13975a_idx"
                    ),
                    models.Index(
                        fields=["relation"], name="beneficiari_relatio_8bf7d4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="beneficiari_status_9ea618_idx"
                    ),
                    models.Index(
                        fields=["last_service_date"],
                        name="beneficiari_last_se_468ae2_idx",
                    ),
                    models.Index(
                        fields=["deleted_at"], name="beneficiari_deleted_e9a7da_idx"
                    ),
                ],
            },
        ),
    ]
