# Generated by Django 5.2.8 on 2025-11-21 17:41

import axis_backend.utils.generators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("Employee", "Employee"), ("Dependent", "Dependent")],
                        db_index=True,
                        help_text="Type of person: Employee or Dependent",
                        max_length=20,
                    ),
                ),
                (
                    "employee_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Admin", "Admin"),
                            ("Manager", "Manager"),
                            ("Staff", "Staff"),
                            ("Volunteer", "Volunteer"),
                        ],
                        db_index=True,
                        help_text="Role within employer organization (EMPLOYEE only)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "employment_start_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Employment start date (EMPLOYEE only)",
                        null=True,
                    ),
                ),
                (
                    "employment_end_date",
                    models.DateField(
                        blank=True,
                        help_text="Employment end date (EMPLOYEE only)",
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("On Leave", "On Leave"),
                            ("Terminated", "Terminated"),
                            ("Suspended", "Suspended"),
                            ("Resigned", "Resigned"),
                        ],
                        db_index=True,
                        help_text="Employment status (EMPLOYEE only)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "qualifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Certifications and role qualifications (EMPLOYEE only)",
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Work areas or departments (EMPLOYEE only)",
                    ),
                ),
                (
                    "preferred_working_hours",
                    models.JSONField(
                        blank=True,
                        help_text="Work schedule for session scheduling (EMPLOYEE only)",
                        null=True,
                    ),
                ),
                (
                    "relationship_to_employee",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Child", "Child"),
                            ("Spouse", "Spouse"),
                            ("Parent", "Parent"),
                            ("Sibling", "Sibling"),
                            ("Grandparent", "Grandparent"),
                            ("Guardian", "Guardian"),
                            ("Friend", "Friend"),
                            ("Neighbor", "Neighbor"),
                            ("Cousin", "Cousin"),
                            ("Other", "Other"),
                        ],
                        db_index=True,
                        help_text="Relationship to primary employee (DEPENDENT only)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_employee_dependent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this dependent is also an employee (spouse working at same org)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Pending", "Pending"),
                            ("Archived", "Archived"),
                            ("Deleted", "Deleted"),
                        ],
                        db_index=True,
                        default="Active",
                        help_text="Current status (determines service eligibility)",
                        max_length=20,
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Most recent service session date",
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact person name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Emergency contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Emergency contact email address",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes and observations",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional flexible attributes",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employer organization (EMPLOYEE only)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="clients.client",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        blank=True,
                        help_text="Guardian user for minors (DEPENDENT only)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guardianships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary employee this dependent is linked to (DEPENDENT only)",
                        limit_choices_to={"person_type": "Employee"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dependents",
                        to="persons.person",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        help_text="Personal demographic information",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="person",
                        to="authentication.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User account for portal/app access",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
                "db_table": "persons",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["person_type"], name="persons_person__6d3413_idx"
                    ),
                    models.Index(fields=["user"], name="persons_user_id_a1e9c7_idx"),
                    models.Index(fields=["profile"], name="persons_profile_0d8a3e_idx"),
                    models.Index(fields=["client"], name="persons_client__932c17_idx"),
                    models.Index(
                        fields=["primary_employee"], name="persons_primary_ea3724_idx"
                    ),
                    models.Index(fields=["status"], name="persons_status_c9efa3_idx"),
                    models.Index(
                        fields=["employee_role"], name="persons_employe_e5077c_idx"
                    ),
                    models.Index(
                        fields=["employment_status"], name="persons_employm_cdf4ce_idx"
                    ),
                    models.Index(
                        fields=["relationship_to_employee"],
                        name="persons_relatio_df6e4d_idx",
                    ),
                    models.Index(
                        fields=["employment_start_date"],
                        name="persons_employm_a5b336_idx",
                    ),
                    models.Index(
                        fields=["last_service_date"], name="persons_last_se_0aed69_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="persons_deleted_dba7b6_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("employment_end_date__isnull", True),
                            (
                                "employment_end_date__gte",
                                models.F("employment_start_date"),
                            ),
                            _connector="OR",
                        ),
                        name="person_employment_end_after_start",
                    )
                ],
            },
        ),
    ]
