# Generated by Django 5.2.8 on 2025-11-25 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_add_user_client_junction_table"),
        ("clients", "0002_client_last_contact_date_client_parent_client_and_more"),
        ("persons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="preferred_working_hours",
        ),
        migrations.RemoveField(
            model_name="person",
            name="qualifications",
        ),
        migrations.AddField(
            model_name="person",
            name="accepts_insurance",
            field=models.BooleanField(
                default=False,
                help_text="Accepts insurance payments (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="availability_schedule",
            field=models.JSONField(
                blank=True,
                help_text="Available hours for sessions (SERVICE_PROVIDER only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Professional biography (SERVICE_PROVIDER only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="can_manage_clients",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Permission to manage client accounts (PLATFORM_STAFF only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="can_manage_services",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Permission to configure services (PLATFORM_STAFF only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="can_view_reports",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Permission to view analytics and reports (PLATFORM_STAFF only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="certifications",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Professional certifications (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="currency",
            field=models.CharField(
                blank=True,
                default="USD",
                help_text="Currency for rates (SERVICE_PROVIDER only)",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="current_client_count",
            field=models.IntegerField(
                default=0,
                help_text="Current number of active clients (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="education",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Educational background (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="employee_department",
            field=models.CharField(
                blank=True,
                help_text="Department within client organization (CLIENT_EMPLOYEE only)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="employee_id_number",
            field=models.CharField(
                blank=True,
                help_text="Employee ID from client organization (CLIENT_EMPLOYEE only)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Service rate per hour (SERVICE_PROVIDER only)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="insurance_providers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of accepted insurance providers (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_accepting_new_clients",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Currently accepting new clients (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_dual_role",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Has multiple roles (e.g., platform staff + client employee)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="languages_spoken",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Languages spoken for sessions (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="license_expiry",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="License expiration date (SERVICE_PROVIDER only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="license_issuing_authority",
            field=models.CharField(
                blank=True,
                help_text="Authority that issued the license (SERVICE_PROVIDER only)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="license_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Professional license number (SERVICE_PROVIDER only)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="max_clients",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum concurrent clients (SERVICE_PROVIDER only)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="profile_photo_url",
            field=models.URLField(
                blank=True,
                help_text="Profile photo URL (SERVICE_PROVIDER only)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="provider_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Type of service (therapist, counselor, psychologist, etc.) (SERVICE_PROVIDER only)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="secondary_person_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PlatformStaff", "Platform Staff"),
                    ("ClientEmployee", "Client Employee"),
                    ("Dependent", "Dependent"),
                    ("ServiceProvider", "Service Provider"),
                ],
                db_index=True,
                help_text="Secondary role if dual role enabled",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="staff_department",
            field=models.CharField(
                blank=True,
                help_text="Department within EAP organization (PLATFORM_STAFF only)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="staff_organization",
            field=models.ForeignKey(
                blank=True,
                help_text="EAP organization (PLATFORM_STAFF only)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="platform_staff",
                to="clients.client",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="staff_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Staff", "Staff"),
                    ("Volunteer", "Volunteer"),
                ],
                db_index=True,
                help_text="Role in EAP organization (PLATFORM_STAFF only)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="years_of_experience",
            field=models.IntegerField(
                blank=True,
                help_text="Years of professional experience (SERVICE_PROVIDER only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Employer organization (CLIENT_EMPLOYEE only)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_employees",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="employee_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("Manager", "Manager"),
                    ("Staff", "Staff"),
                    ("Volunteer", "Volunteer"),
                ],
                db_index=True,
                help_text="Role within employer organization (CLIENT_EMPLOYEE only)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="employment_end_date",
            field=models.DateField(
                blank=True,
                help_text="Employment end date (CLIENT_EMPLOYEE only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="employment_start_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Employment start date (CLIENT_EMPLOYEE only)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("On Leave", "On Leave"),
                    ("Terminated", "Terminated"),
                    ("Suspended", "Suspended"),
                    ("Resigned", "Resigned"),
                ],
                db_index=True,
                help_text="Employment status (CLIENT_EMPLOYEE only)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="person_type",
            field=models.CharField(
                choices=[
                    ("PlatformStaff", "Platform Staff"),
                    ("ClientEmployee", "Client Employee"),
                    ("Dependent", "Dependent"),
                    ("ServiceProvider", "Service Provider"),
                ],
                db_index=True,
                help_text="Primary person type: PlatformStaff, ClientEmployee, Dependent, or ServiceProvider",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="primary_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary client employee this dependent is linked to (DEPENDENT only)",
                limit_choices_to={"person_type": "ClientEmployee"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dependents",
                to="persons.person",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="specializations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Areas of expertise (SERVICE_PROVIDER only)",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["is_dual_role"], name="persons_is_dual_a5fbf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["secondary_person_type"], name="persons_seconda_c02d27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["staff_organization"], name="persons_staff_o_dc0b8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["staff_role"], name="persons_staff_r_890ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["can_manage_clients"], name="persons_can_man_840fb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["can_manage_services"], name="persons_can_man_afb725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["can_view_reports"], name="persons_can_vie_5675b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["provider_type"], name="persons_provide_2c10f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["license_number"], name="persons_license_e4dc45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["license_expiry"], name="persons_license_62f374_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["is_accepting_new_clients"], name="persons_is_acce_97fc38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["person_type", "status"], name="persons_person__5c5b94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["person_type", "client"], name="persons_person__817606_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["person_type", "staff_organization"],
                name="persons_person__5129ce_idx",
            ),
        ),
    ]
