# Generated by Django 5.2.8 on 2025-11-21 17:15

import axis_backend.utils.generators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KPIType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="KPI type name (e.g., 'Utilization', 'Satisfaction', 'Outcome')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Type purpose and measurement approach",
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        blank=True,
                        help_text="Relative importance for scoring (higher = more important)",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional type attributes",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Type",
                "verbose_name_plural": "KPI Types",
                "db_table": "kpi_types",
                "ordering": ["-weight", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="kpi_types_name_100696_idx"),
                    models.Index(
                        fields=["deleted_at"], name="kpi_types_deleted_fceef7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="KPI name (e.g., 'Session Attendance Rate')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed KPI definition and purpose",
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Measurement unit (e.g., '%', 'count', 'hours')",
                        max_length=50,
                    ),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("Percentage", "Percentage"),
                            ("Count", "Count"),
                            ("Score", "Score"),
                            ("Time", "Time"),
                        ],
                        help_text="Unit classification",
                        max_length=20,
                    ),
                ),
                (
                    "target_value",
                    models.CharField(
                        blank=True,
                        help_text="Target/goal value (as string for flexibility)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "calculation_method",
                    models.TextField(
                        blank=True,
                        help_text="How KPI is calculated or measured",
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Once", "Once"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        db_index=True,
                        help_text="Measurement frequency",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Visible in public reports",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional KPI configuration",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client-specific KPI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contract-specific KPI",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="contracts.contract",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        help_text="KPI classification",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpis",
                        to="kpis.kpitype",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPIs",
                "db_table": "kpis",
                "ordering": ["type", "name"],
            },
        ),
        migrations.CreateModel(
            name="KPIAssignment",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=axis_backend.utils.generators.generate_cuid,
                        editable=False,
                        max_length=25,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "target_value",
                    models.CharField(
                        blank=True,
                        help_text="Contract-specific target (overrides KPI default)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Once", "Once"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Annually", "Annually"),
                        ],
                        help_text="Measurement and reporting frequency",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Ongoing", "Ongoing"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        help_text="Assignment status",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True, help_text="KPI tracking start date"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="KPI tracking end date", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Assignment notes and context", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Assignment-specific data and measurements",
                        null=True,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client for whom KPI is tracked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assignments",
                        to="clients.client",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="Contract under which KPI is measured",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kpi_assignments",
                        to="contracts.contract",
                    ),
                ),
                (
                    "kpi",
                    models.ForeignKey(
                        help_text="KPI being tracked",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="kpis.kpi",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Assignment",
                "verbose_name_plural": "KPI Assignments",
                "db_table": "kpi_assignments",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["kpi"], name="kpi_assignm_kpi_id_fe0e0a_idx"),
                    models.Index(
                        fields=["contract"], name="kpi_assignm_contrac_89e31d_idx"
                    ),
                    models.Index(
                        fields=["client"], name="kpi_assignm_client__f1c3ae_idx"
                    ),
                    models.Index(
                        fields=["status"], name="kpi_assignm_status_363cfa_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="kpi_assignm_start_d_985b50_idx"
                    ),
                    models.Index(
                        fields=["deleted_at"], name="kpi_assignm_deleted_a14b9f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["name"], name="kpis_name_90ce4e_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["type"], name="kpis_type_id_a33d78_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["client"], name="kpis_client__cd41dc_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["contract"], name="kpis_contrac_918878_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["is_public"], name="kpis_is_publ_92ca02_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["frequency"], name="kpis_frequen_c7af76_idx"),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(fields=["deleted_at"], name="kpis_deleted_95e47f_idx"),
        ),
    ]
